### ISSUE TITLE
Help doing export to Onnx?

### ISSUE THREAD

**Issue by artificalaudio** [daquexian/faster-rwkv#17]
hey, do you need any help with the export to onnx script, I'm happy to put in some time to help figure this out. 

I've seen a few examples, and look like it just needs setting up with dummy inputs. There's also onnx addons, that allow embedding of the tokeniser which would be nice to figure out. 

I'm on the RWKV discord if you fancy a more direct chat about it.

**Comment by AsakusaRinne** [comment]
@daquexian

**Comment by daquexian** [comment]
Update: after communication on discord, @artificalaudio found that onnx is indeed unnecessary to what he wants (generate midi music). This is his demo based on faster rwkv ncnn backend: https://www.youtube.com/watch?v=2EoCajfyR3k
